### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by roliveri**
Updated README.md to document the creation of Azure service principa for use by the source.

### CODE REVIEW

**Review by syncrou — APPROVED** [review]
LGTM 👍 @slemrmartin can you take a look?

**Review by slemrmartin — APPROVED** [review]
awesome! :+1:

**Comment by slemrmartin** [comment]
@roliveri it seems you don't have a fork, this is commited directly to upstream

**Comment by roliveri** [comment]
@slemrmartin Thanks for letting me know. I don't know how I let that happen.

**Pull request merged**
